### PR TITLE
oui DB update

### PR DESCRIPTION
**Pull request by dor-alt**

### CODE REVIEW

**Comment by sophron** [comment]
Nice. That was fast. A few more things to complete this PR.

1) Remove `update_oui_list` and `update_oui_db.py` from your PR. There's no need to include it in our main repository since it's only useful for us (the developers) and not Wifiphisher users.
 
2) If you noticed our format in `wifiphisher-mac-prefixes`, it is the following:

\<BSSID\>|\<VENDOR\>|(LOGO_FILE)

For example an entry can be: "1CBDB9|D-Link International|dlink.png"

The third part, the logo, is optional and is actually deprecated. We used to use this information when we were displaying a logo in our "Firmware Upgrade" scenario. We are not doing this anymore (due to copyright reasons) so we are free to remove these and change our format simply to \<BSSID\>|\<VENDOR\>. Do you mind doing this change too?

3) After you are finished, you will have to "squash" your commits in one commit in order for us to have a clean history in the repo. There are many tutorials on the Internet that can help you, here's one: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

After that, I will proceed with merging this.

**Comment by blackHatMonkey** [comment]
@sophron maybe we can create a small bash script that does this so we can periodically run this?

**Comment by dor-alt** [comment]
1.I can't find a way to delete commits, do I have to close this PR and create a new one to delete the unncessery files?
And I understand what you're saying about it's not needed for the users, but since you said you want it to be always updated altough you also want it to work without updaing via internet, I just thought you'll want this script saved somewhere, so if you or a user wants to update it manually from the svn source it will be possible with running it. 
2. Will do
3. I'll check this, I'm still new with github

Thanks

**Comment by sophron** [comment]
@blackHatMonkey The script that @dor-alt has attached can probably be used for this purpose.

**Comment by dor-alt** [comment]
@sophron on the latest project I've worked on , we had some "utils" directory, that we've saved those kind of scripts somewhere in the projects

**Comment by sophron** [comment]
@dor-alt No. You just need to "git rm" the files and then "push" again. 

This is not really something that a user has to do. The user doesn't even need to know the technical details or how exactly we are using this database.

We could have a specific branch for all of our "development" or "maintenance" tools. Your script could fit there. @blackHatMonkey's script on PR #956 could also fit there. What do you think?

Take your time with git! A good learning spot to start lies here: https://lab.github.com/

**Comment by blackHatMonkey** [comment]
@sophron We could just put all of our scripts in a `script/` directory. Those won't be included by `pip` anyway.

**Comment by sophron** [comment]
@dor-alt, I see that you created #969 too. Which PR do you want us to follow?

**Comment by dor-alt** [comment]
Hi
I tried to squash (I know it as merge ) all commits to one single commit, I followed this too https://blog.github.com/2016-04-01-squash-your-commits/
but from what I understand only the project owner can approve the merge,

**Comment by dor-alt** [comment]
https://github.com/wifiphisher/wifiphisher/pull/969  - is where I also deleted the file I created by mistake, so I guess I will close this one and we'll follow 969

**Pull request closed without merging**
