### PR TITLE
Add Wi-Fi Network Manager Connect screen for iOS

### PR DESCRIPTION
**Pull request by smarty-mcfly**
The iOS targeted passphrase screen looks similar to the regular iOS
Wi-Fi passphrase screen on iOS.

### CODE REVIEW

**Comment by smarty-mcfly** [comment]
ios_wifi_login

**Comment by Bsoft2007** [comment]
it is suposed to show like that on Android too?

**Comment by Bsoft2007** [comment]
@smarty-mcfly I've tested your index.html scenario.
Can you add this IOS scenario into Device Modal scenario, so that we have a IOS working scenario?

**Comment by smarty-mcfly** [comment]
> @smarty-mcfly I've tested your index.html scenario.
> Can you add this IOS scenario into Device Modal scenario, so that we have a IOS working scenario on Device Modal Scenario too?

What is the Device Modal Scenario? Can you point me to it?

**Comment by Bsoft2007** [comment]
Yes i can, u can find it on the 'extra-phishing-pages', here: https://github.com/wifiphisher

**Comment by smarty-mcfly** [comment]
The Device Modal seems like a different scenario about a firmware upgrade. This one is about the network connection manager. I don’t think it makes sense to duplicate it.

**Comment by Bsoft2007** [comment]
@smarty-mcfly, im certain it's a network manager, and it works ok with Windows and android, but not on IOS. So it would be great if you could have IOS working too. Do you think it's possible ?

**Comment by sophron** [comment]
Sorry for the late response, I was on vacation.

This looks like a great addition. I will review as soon as possible.

**Comment by sophron** [comment]
A nice contribution. Thanks again @smarty-mcfly.

**Pull request merged**
