### PR TITLE
Update wifiphisher-mac-prefixes

### PR DESCRIPTION
**Pull request by agentzex**

### CODE REVIEW

**Comment by sophron** [comment]
This is the continue of #966.

@dor-alt A squash is different than merge.

In simple terms, merge is when you apply the commits of a branch into another branch. For example, when your PR is ready, I will apply your commits to "master" branch.

Squash is when, in a branch, you want to put together a number of commits into one single commit. For example, you have seven commits right now. If you squash them, you will only have one commit.

Have a look at the guide that I sent you earlier: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

After the `git rebase -i HEAD~7`, you will have to do a `git push -f` to force the update of your branch.

Let me know if you have any issues.

**Comment by dor-alt** [comment]
And you can't do that in here via github? or it's only possible via some git client?

**Comment by sophron** [comment]
You can do it via command line. If you are using a specific git client, there may be an option there too.

**Comment by dor-alt** [comment]
I think it worked but not sure, I downloaded sourcetree , and I it seems my commits are already pushed after I did the rebase thing

**Comment by sophron** [comment]
No, I think you haven't understood what "squash" means. You may have confuse it with the simple "rebase" that we do when we want to solve any conflicts. Even though we use "rebase" to do squashing.

See here: https://github.com/wifiphisher/wifiphisher/pull/967/commits

Brian's PR has only one commit because he squashed his commits.

Now, look at yours: https://github.com/wifiphisher/wifiphisher/pull/969/commits

You have 5 commits. If you squash your commits, you should have a single commit there.

I assume you run a Linux, right? My recommendation is to learn about git before proceeding. It's necessary to learn to use git basics via command line too. Many features of git are not supported in other git clients (that are integrated in IDEs for example).

**Comment by dor-alt** [comment]
I read and understood what squash means , I followed the link you gave and via the GIT command line I did:
git rebase -i HEAD~7
Then it showed me the 7 commits, and I read I need to modify 'pick' to 'squash' , so I did. Then I saved the file.
After that it asked to give some kind of comment to all of the commits so I did.
I then did 'git push 'my_branch_name' master -f'
It seemed to work and returned correctly, I just have no idead how it should look on the UI here on github after I did it (I did worked with git in the past , just not github, I thought there will be an easy way to just do everything from the browser with github)

**Comment by sophron** [comment]
>Then it showed me the 7 commits, and I read I need to modify 'pick' to 'squash' , so I did. Then I saved the file.

The first commit needs to be `pick`, the next 6 need to be `squash`. Make sure that the file was saved indeed and you didn't just exit.

> I then did 'git push 'my_branch_name' master -f'

Maybe here's the mistake. You should not push to master. You should push to your remote `my_branch_name`.  A `git push -f` should automatically do that for you.

>It seemed to work and returned correctly, I just have no idead how it should look on the UI here on github after I did it (I did worked with git in the past , just not github, I thought there will be an easy way to just do everything from the browser with github)

Git is a complex utility and Github is rather limited.

Take your time. If you are still unable to figure it out, feel free to start from the beginning and make a new PR.

**Comment by dor-alt** [comment]
OK cool, I now did it again with only 'git push -f' and now I see on github this 
cap

Do I need to press on the 'compare & pull request' again? cause this is the last step I'm missing, after I pushed via git command line

Thanks

**Comment by sophron** [comment]
You have two different remote branches: one is dor-alt/master and another is dor-alt/master-dor-alt.

When you first created this Pull Request, your intention was to merge dor-alt/master with wifiphisher/master. However, your latest change was pushed in dor-alt/master-dor-alt instead of dor-alt/master. That's why Github is asking you to create another PR to merge dor-alt/master-dor-alt with wifiphisher/master.

You can either push to the correct remote branch (that is, dor-alt/master) or close this PR and open another (e.g. with dor-alt/master-dor-alt). You can also `rm -rf` everything, `git clone` the wifiphisher repo and start from the beginning.

I understand how git can be complex for beginners. Understanding what is happening and getting knowledge is the most important in this phase :)

**Comment by dor-alt** [comment]
OK, I decided to start all over again, created a new PR #971 
I followed this https://gist.github.com/MarcDiethelm/7303312

So I think I had it right this time, let me know

If this guide is correct, it means each time I change some code locally , I need to create a new branch for it? like each time I'll delete an old branch, create new branch, add code, push, then after it is approved, delete that branch again? sounds redundant and weird :)

**Pull request closed without merging**
