### PR TITLE
Created Logger function

### PR DESCRIPTION
**Pull request by alexsalvetti**
Created Logger function for having a log file of the terminal in case of crash or just for save the information collected.

### CODE REVIEW

**Comment by blackHatMonkey** [comment]
Thanks for your contribution. We will review the PR and let you know. :smile:

**Comment by fafualex** [comment]
I would like to improve the function writing only when the lines on terminal changes values for having a smaller log. 
Because when you let the script going for a while the log file gain too much lines and many of them are equal.. 
I have tried to implement the function with:

`uniquelines = set(open('logfile.log').readlines())
logfile = open('logfile_mod.log', 'w').writelines(set(sorted(uniquelines)))`

but the lines are not in the same order like the original log file.

**Comment by sophron** [comment]
Hi @fafualex,

Sorry for the late response. Things were pretty busy the past weeks.

Having a logger is definitely a feature that we want to include. I can imagine people running the tool on hidden small devices (e.g. Raspberry PI) for hours.

However, logging all the output from the terminal will result to an ugly report not easy to read. If you want to work on this, let me know and we can discuss the design of the implementation together.

**Comment by blackHatMonkey** [comment]
I'm closing this PR since the contents no longer apply.

**Pull request closed without merging**
