### PR TITLE
Fixed exception for not waiting sniff thread done

### PR DESCRIPTION
**Pull request by anakin1028**
When use the following command:
`wifiphisher -aI wlan0 -nJ -p oauth-login`
will occur the following exception:

exception_for_not_waiting_sniff_thread_done

This is beacuse we don't wait the sniff thread done and just set the interface mode to managed from the monitor mode.
Though the functionality is not being affected, maybe we can fix it to remove the annoying trace stack.

Another thing is similarly when the user ends the wifiphisher, the deauth thread should also be wait for done.

### CODE REVIEW

**Comment by sophron** [comment]
This looks good!

Thank you @anakin1028.

**Comment by blackHatMonkey** [comment]
I know this has been already merged but perhaps a better way for it was to joined the threads inside the class rather than the outside and add a timeout in case it ever hangs.

**Comment by anakin1028** [comment]
To do that we need to add the sniff_packet_thread and channel_hop_thread as the attributes of the 
`class AccessPointFinder` and join them at the method `stop_finding_access_points`. Do you think this way is OK?

**Comment by blackHatMonkey** [comment]
@anakin1028 Yes it would be the same as `deauth`. Just note that don't set the them on the `__init__` method but somewhere else as it makes unittesting impossible that way. Also a timeout needs to be set so it doesn't hang forever.

**Comment by anakin1028** [comment]
@blackHatMonkey ok, I will fix it. Thanks for your suggestion 👍

**Pull request merged**
