### PR TITLE
Updated copyright year

### PR DESCRIPTION
**Pull request by LameLemon**
#1108 and #1120 changed the copyright years in `firmware-upgrade/html/index.html` and `firmware-upgrade/html/loading.html` however the year in `firmware-upgrade/html/upgrading.html` was left at 2016.

It has been changed to 2019.

### CODE REVIEW

**Comment by LameLemon** [comment]
Upon further inspection, should I just add the following the to the script? It would seem to be a more permanent solution for all the html files.
```

    var theDate=new Date() 
    document.getElementsByClassName("text-muted")[0].innerHTML = "©  " + theDate.getFullYear() + ", All Rights Reserved.";
    
```

**Comment by sophron** [comment]
Hi @LameLemon, 

This is great! Do you think you can add this JS snippet to the rest of the phishing pages that contain a trademark too?

Thanks!

**Comment by LameLemon** [comment]
Hello @sophron, 

The only html pages I'm aware of that have the trademark are `index.html`, `upgrading.html`and `loading.html`. I've added them to the last two pages but not `index.html` since it would interfere with the template (I think).

**Comment by sophron** [comment]
You can do it on `index.html` too. But I was actually thinking the rest of the phishing scenarios (e.g. oauth-login).

**Comment by LameLemon** [comment]
Sure thing, I went through the other phishing-pages the other scenarios don't have a trademark in their html files. `oauth-login/html/index.html` had the trademark in the comment which I've updated. 

As for `firmware-upgrade/html/index.html` I've updated the code as shown below. However, I'm not able to test and see if the vendor name appears since I am unable to run the program with my current setup. So that  is the only part that remains untested. 
```
document.getElementsByClassName("text-muted")[0].innerHTML = "© {{ target_ap_vendor }} " + theDate.getFullYear() + ", All Rights Reserved.";
```
The other pages I've run and work perfectly fine.

**Comment by sophron** [comment]
I thought there was a date in oauth-login, my bad.

I can test if everything is working properly. There's one last thing yo do from your side: squashing. It is important to squash your commits in order for us to have a clean history in the repo. Here's a tutorial that may help you: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by LameLemon** [comment]
Sorry about that oversight on my part, forgot to squash the commits.

**Comment by sophron** [comment]
Merged. Thank you.

**Pull request merged**
