### PR TITLE
Refactor and fix the ap/template selection tui issues

### LINKED ISSUE #662: UnboundLocalError: local variable 'row_number' referenced before assignment
After running wifiphisher and scaning access points and selecting any AP it showed me this
```
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.3GIT at 2017-07-03 18:38
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:47:29:a1
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:b2:63:be
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 653, in start
    template = tui_template_obj.gather_info(args.phishingscenario, self.template_manager)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/tui.py", line 80, in gather_info
    template_names)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/tui.py", line 193, in display_info
    row_number += 2
UnboundLocalError: local variable 'row_number' referenced before assignment
```

### PR DESCRIPTION
**Pull request by anakin1028**
@sophron @blackHatMonkey 

This PR should fix #662 

We have some bugs for the TUI, and this PR should fix them all. The issues I have fixed:

  * When the screen terminal is too small, the AP selection/Phishing template curses section will
     be broken.
  * Let the users use arrow key to select the phishing scenarios cross pages [i.e. just like AP selection]
  * pylint fixed.

### CODE REVIEW

**Comment by sophron** [comment]
@blackHatMonkey Wanna see this one? :)

**Comment by blackHatMonkey** [comment]
@sophron Sure I will take a look at it this weekend 😄 .

**Comment by anakin1028** [comment]
@blackHatMonkey thanks~~

**Comment by sophron** [comment]
@blackHatMonkey I think you are busy these days, so i can review & merge this PR for you tomorrow.

**Pull request merged**
