### PR TITLE
Use curses for the main terminal and template selecton

### PR DESCRIPTION
**Pull request by anakin1028**
Based on the @blackHatMonkey's work, I have created another two curses sections for the main terminal and the template selection. 

The following is the screen shot of the template selection I currently create:

phishing_scenarios

And the main terminal one is shown in #611

### CODE REVIEW

**Comment by sophron** [comment]
Great stuff as always. I'll test tomorrow.

**Comment by sophron** [comment]
I haven't tested yet, but based on the screenshots there may be some spacing issues. Make sure you put a space after "[-]" and before "Wifiphisher" on the top-right box too.

**Comment by anakin1028** [comment]
ok I'll fix that : )

**Comment by sophron** [comment]
Do you think we can make the Template Selection like our AP selection? Use arrows and "Enter" to select the scenario that we want to use instead of writing a number?

**Comment by anakin1028** [comment]
I will think about that part.

**Comment by anakin1028** [comment]
@sophron Using arrow and enter for template selection now : )
I'll solve the conflicts in the next few days

**Pull request merged**
