### PR TITLE
chore: simplify ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by blackHatMonkey**
Remove ISSUE_TEMPLATE as it never helped reduce the work needed for debugging of the issues. In fact in some cases it increases the workload needed.

### CODE REVIEW

**Comment by anakin1028** [comment]
I'm OK with this. Issue reporters report the issues follow their logic may be better than restricting the issue format now.

**Comment by sophron** [comment]
I don't see how the ISSUE_TEMPLATE causes problems. I agree though that in most cases it is ignored. I believe we should focus on changing the required information, maybe making it more minimal.

**Comment by blackHatMonkey** [comment]
@sophron I just simplified the template. Let me know if you think any more changes should be made.

**Comment by sophron** [comment]
I updated `ISSUE_TEMPLATE` with the necessary information. It should be good now.

**Pull request closed without merging**
