### PR TITLE
Added the gopro-phish scenario

### PR DESCRIPTION
**Pull request by Splinter0**
Hey guys, this is a new scenario i've created.
It basically asks for the GoPro password, a really cool feature is that there is also a confirm password that makes everything more realistic and it also provides you more chances to have the actual password.
If you wanna take a look at the code without scrolling into the wifiphisher folders 

<a href="https://github.com/Splinter0/GoPro-Phish" target="_blank">Code on my repo</a>

I hope you'll like it

<a href="https://github.com/Splinter0/" target="_blank">Splinter</a>

### CODE REVIEW

**Comment by Splinter0** [comment]
@sophron

**Comment by blackHatMonkey** [comment]
Hi @Splinter0 Thanks for contributing. We will review and let you know if any changes needs to be made.

**Comment by sophron** [comment]
Hi @Splinter0,

I just created a <a href="https://github.com/wifiphisher/extra-phishing-pages">different repository</a> for extra community-built scenarios. I believe your page that targets a very specific device (GoPro) fits better there, so I would advise you to make a PR there instead. I will put many more scenarios (bringing back some old ones) in that repo soon enough.

**Comment by Splinter0** [comment]
Hi @sophron thanks a lot!
I'll make a PR in that new repository soon.

**Comment by alternatexp** [comment]
How could this be implemented as a captive portal?

I can imagine this to be an excellent bettercap module.

**Comment by blackHatMonkey** [comment]
I'm closing this since a new PR has been made [here](https://github.com/wifiphisher/extra-phishing-pages/pull/1).

**Pull request closed without merging**
