### PR TITLE
minifix parameter

### PR DESCRIPTION
**Pull request by josep11**

### CODE REVIEW

**Comment by josep11** [comment]
I don't get why are you closing the PR. In the last version there is no -jI parameter:

image

And also the -dC parameter is not properly documented:

image

Please merge

**Comment by josep11** [comment]
I think this minor fix should be merged. @sophron, @blackHatMonkey, @anakin1028, @yasoob

**Comment by sophron** [comment]
Hi @josep11,

You should have created a different PR for each "fix". 

I disagree with adding "sudo" in the Usage section. Wifiphisher can run on systems without "sudo" installed.

**Comment by josep11** [comment]
Ok, now we can merge #1492

**Pull request closed without merging**
