### PR TITLE
fixed the malformed beacon frame which doesn't contain the info field

### PR DESCRIPTION
**Pull request by anakin1028**
Another malformed beacon frame issue. The following is the sniffer capture and the pdb session:

The following is the screenshot of wifiphisher:

### CODE REVIEW

**Comment by blackHatMonkey** [comment]
Thanks @anakin1028 I will test it and let you know.

**Comment by blackHatMonkey** [comment]
Also @anakin1028 if you have time can you look into simplifying `_find_encryption_type` method. Perhaps we can find a better way of doing it.

**Comment by anakin1028** [comment]
@blackHatMonkey  sure, I'll take a look about it~

**Comment by anakin1028** [comment]
@blackHatMonkey, I have seen the code for getting the encryption type. The code seems no problem for me. Since the order of the information elements are not required to put in specific order, we cannot index the RSN or WPA IE directly, thus needs to loop the IEs to get the particular ID.

**Pull request merged**
